spring:
  datasource:
    url: "jdbc:postgresql://db:5432/postgres"
    username: "postgres"
    password: "postgres"
    initialization-mode: always
    schema: classpath:/schema.sql
  flyway:
    enabled: true
    baselineOnMigrate: true
  output:
    ansi:
      enabled: always